language: generic

sudo: required

dist: trusty

matrix:
  fast_finish: true
  include:
    - env: COQ_VERSION="trunk"    COQ_PACKAGE="coq"      PPA="ppa:jgross-h/coq-trunk-daily"        TARGETS="coq"
    - env: COQ_VERSION="v8.6"     COQ_PACKAGE="coq"      PPA="ppa:jgross-h/coq-8.6-daily"          TARGETS="coq"
    - env: COQ_VERSION="8.6"      COQ_PACKAGE="coq-8.6"  PPA="ppa:jgross-h/many-coq-versions"      TARGETS="coq"
  allow_failures:
    - env: COQ_VERSION="v8.6"     COQ_PACKAGE="coq"      PPA="ppa:jgross-h/coq-8.6-daily"          TARGETS="coq"
    - env: COQ_VERSION="trunk"    COQ_PACKAGE="coq"      PPA="ppa:jgross-h/coq-trunk-daily"        TARGETS="coq"

before_install:
  - if [ ! -z "$PPA" ]; then sudo add-apt-repository "$PPA" -y; fi
  - sudo apt-get update -q
  - sudo apt-get install $COQ_PACKAGE -y

before_script:
  - uname -a
  - source ./etc/ci/travis_keep_alive.sh

script: make corn TIMED=1 -j2 && make $TARGETS TIMED=1 -j2

after_success:
  - kill $PID_KEEP_ALIVE
