language: generic

sudo: required

dist: trusty

addons:
  apt:
    sources:
      - avsm
    packages:
      - opam

cache:
  apt: true
  directories:
    - $HOME/.opam

env:
  - COQ_VERSION="8.6"
  - COQ_VERSION="8.6.dev"
  - COQ_VERSION="dev"

matrix:
  fast_finish: true
  allow_failures:
    - env: COQ_VERSION="8.6.dev"
    - env: COQ_VERSION="dev"

before_install:
  - export NJOBS=2
  - if ! [ -e .opam ]; then opam init -j ${NJOBS} --compiler=system -n -y; fi
  - eval $(opam config env)
#  - opam config var root
#  - opam install -j ${NJOBS} -y camlp5 ocamlfind
  - opam list
  - opam add coq-extra-dev https://coq.inria.fr/opam/extra-dev
  - opam add coq-core-dev https://coq.inria.fr/opam/core-dev
  - opam install -j ${NJOBS} -y coq.${COQ_VERSION}
  - opam install -j ${NJOBS} -y coq-corn

before_script:
  - uname -a

script: make TIMED=1 -j2
